services:
  db:
    container_name: dbdemo
    image: mysql
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      POSTGRES_PASSWORD: password
  web:
    container_name: dbdemoapp
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/db-demo
    ports:
      - "3005:3000"
    depends_on:
      - db
