services:
  db:
    container_name: dbdemo
    build: ./mysql/
    volumes:
      - ./mysql/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: db_demo
      MYSQL_ROOT_PASSWORD: rootpassword
  web:
    container_name: dbdemoapp
    build: ./rails/
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/db-demo
    ports:
      - "3005:3000"
    depends_on:
      - db
